### ISSUE TITLE
posix-file-permissions returns java.util.Hashset

### ISSUE THREAD

**Issue by egli** [ToBeReplaced/nio.file#3]
If I read `posix-file-permissions` correctly it returns a `java.util.HashSet`. This caught me by surprise when I was trying to `conj` another permission to it. I guess I expected a clojure set. This might be more idiomatic.

I'd rather do
```
(conj (nio/posix-file-permissions dir) (nio/posix-file-permission :group-write))
```
instead of
```
(doto (nio/posix-file-permissions dir) (.add (nio/posix-file-permission :group-write)))
```

**Comment by ToBeReplaced** [comment]
I agree. A set still works with `set-posix-file-permissions!` as well.

Fixed via 4ee6e8a87919b416ecbf2e5bf6aaa57b2f7d2ee8 .

If this meets your needs, please close.

**Comment by egli** [comment]
Thanks, perfect. Now all I need is a new release on clojars :-)

**Comment by egli** [comment]
Thank you very much for the new release
